[package]
name = "nom_sql_learning"
version = "0.1.0"
authors = ["dyy <yayi_du@kingdee.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "^1.2.4"